export const MemesData = [
  {
    id: "1",
    imageUrl: "https://i.imgflip.com/1ur9b0.jpg",
    captionTop: "When the code",
    captionBottom: "finally works at 3 AM",
    creator: "code_guy",
    createdAt: Date.now() - 86400000,
    upvotes: 123,
    downvotes: 7,
    views: 2031,
    commentsCount: 14,
    tags: ["relatable", "developer"],
  },
  {
    id: "2",
    imageUrl: "https://i.imgflip.com/30b1gx.jpg",
    captionTop: "Deploying on Friday",
    captionBottom: "What could go wrong?",
    creator: "dev_jane",
    createdAt: Date.now() - 172800000,
    upvotes: 87,
    downvotes: 4,
    views: 1400,
    commentsCount: 9,
    tags: ["devlife", "fail"],
  },
  {
    id: "3",
    imageUrl: "https://i.imgflip.com/3si4.jpg",
    captionTop: "Me reading legacy code",
    captionBottom: "Why is this even here?",
    creator: "senior_sufferer",
    createdAt: Date.now() - 3600000,
    upvotes: 150,
    downvotes: 2,
    views: 3090,
    commentsCount: 27,
    tags: ["legacy", "confused"],
  },
  {
    id: "4",
    imageUrl: "https://i.imgflip.com/1bij.jpg",
    captionTop: "Client: Can we make it blue?",
    captionBottom: "Designer: Which blue?",
    creator: "uiux_master",
    createdAt: Date.now() - 432000000,
    upvotes: 213,
    downvotes: 10,
    views: 5023,
    commentsCount: 36,
    tags: ["design", "clientlife"],
  },
  {
    id: "5",
    imageUrl: "https://i.imgflip.com/26am.jpg",
    captionTop: "Manager: It’s just a small fix",
    captionBottom: "The fix:",
    creator: "scrum_slave",
    createdAt: Date.now() - 7200000,
    upvotes: 334,
    downvotes: 5,
    views: 6501,
    commentsCount: 49,
    tags: ["bugs", "developer"],
  },
  {
    id: "6",
    imageUrl: "https://i.imgflip.com/2hgfw.jpg",
    captionTop: "When AI does your job better",
    captionBottom: "Just smile and optimize",
    creator: "futureproof_dev",
    createdAt: Date.now() - 300000000,
    upvotes: 189,
    downvotes: 3,
    views: 3471,
    commentsCount: 21,
    tags: ["ai", "automation"],
  },
  {
    id: "7",
    imageUrl: "https://i.imgflip.com/4/4t0m5.jpg",
    captionTop: "Frontend devs when",
    captionBottom: "the button moves by 1px",
    creator: "pixel_perfect",
    createdAt: Date.now() - 180000000,
    upvotes: 99,
    downvotes: 6,
    views: 2300,
    commentsCount: 13,
    tags: ["frontend", "css"],
  },
  {
    id: "8",
    imageUrl: "https://i.imgflip.com/5ehz.jpg",
    captionTop: "You said you tested it...",
    captionBottom: "on your machine?",
    creator: "qa_destroyer",
    createdAt: Date.now() - 500000000,
    upvotes: 261,
    downvotes: 12,
    views: 4120,
    commentsCount: 30,
    tags: ["qa", "testing"],
  },
  {
    id: "9",
    imageUrl: "https://i.imgflip.com/1g8my4.jpg",
    captionTop: "When you fix 1 bug",
    captionBottom: "but 2 more appear",
    creator: "bug_summoner",
    createdAt: Date.now() - 240000000,
    upvotes: 312,
    downvotes: 8,
    views: 7003,
    commentsCount: 42,
    tags: ["bugs", "debugging"],
  },
  {
    id: "10",
    imageUrl: "https://i.imgflip.com/1otk96.jpg",
    captionTop: "New dev be like",
    captionBottom: "'What's production?'",
    creator: "mentor_max",
    createdAt: Date.now() - 90000000,
    upvotes: 122,
    downvotes: 2,
    views: 1984,
    commentsCount: 11,
    tags: ["junior", "onboarding"],
  },
];

